/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;
import Controller.RentalController;
import javax.accessibility.AccessibleContext;
import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JRootPane;
import javax.swing.JScrollPane;
import javax.swing.JTable;
import javax.swing.JTextField;
/**
 *
 * @author Lab Informatika
 */
public class DashboardPage extends javax.swing.JFrame {

    /**
     * Creates new form DashboardPage
     */
    RentalController rc;
    public DashboardPage() {
        initComponents();
        rc = new RentalController(this);
        rc.isiTabel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTablerental = new javax.swing.JTable();
        jLabelid = new javax.swing.JLabel();
        jLabelnama = new javax.swing.JLabel();
        jLabelnama1 = new javax.swing.JLabel();
        jLabeljenismobil = new javax.swing.JLabel();
        jLabeldurasi = new javax.swing.JLabel();
        jLabeltotalbiaya = new javax.swing.JLabel();
        jLabelstatuspembayaran = new javax.swing.JLabel();
        jTextFieldid = new javax.swing.JTextField();
        jTextFieldkontak = new javax.swing.JTextField();
        jTextFieldjenismobil = new javax.swing.JTextField();
        jTextFielddurasi = new javax.swing.JTextField();
        jTextFieldnama = new javax.swing.JTextField();
        jTextFieldtotalbiaya = new javax.swing.JTextField();
        jTextFieldstatuspembayaran = new javax.swing.JTextField();
        Tambah = new javax.swing.JButton();
        jButtonupdate = new javax.swing.JButton();
        jButtondelete = new javax.swing.JButton();
        jButtonclear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTablerental.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "id", "nama", "kontak", "jenis_mobil", "durasi", "total_biaya", "status_pembayaran"
            }
        ));
        jTablerental.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTablerentalMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTablerental);

        jLabelid.setText("id");

        jLabelnama.setText("Nama");

        jLabelnama1.setText("Kontak");

        jLabeljenismobil.setText("Jenis Mobil");

        jLabeldurasi.setText("Durasi");

        jLabeltotalbiaya.setText("Total Biaya");

        jLabelstatuspembayaran.setText("Status Pembayaran");

        jTextFieldid.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldidActionPerformed(evt);
            }
        });

        jTextFieldtotalbiaya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldtotalbiayaActionPerformed(evt);
            }
        });

        jTextFieldstatuspembayaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldstatuspembayaranActionPerformed(evt);
            }
        });

        Tambah.setText("Tambah");
        Tambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TambahActionPerformed(evt);
            }
        });

        jButtonupdate.setText("Update");
        jButtonupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonupdateActionPerformed(evt);
            }
        });

        jButtondelete.setText("delete");
        jButtondelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtondeleteActionPerformed(evt);
            }
        });

        jButtonclear.setText("Clear");
        jButtonclear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonclearActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 518, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(75, 75, 75)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabelstatuspembayaran)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextFieldstatuspembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabelid)
                            .addComponent(jLabelnama)
                            .addComponent(jLabelnama1)
                            .addComponent(jLabeljenismobil)
                            .addComponent(jLabeldurasi)
                            .addComponent(jLabeltotalbiaya))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextFielddurasi)
                            .addComponent(jTextFieldjenismobil)
                            .addComponent(jTextFieldkontak)
                            .addComponent(jTextFieldnama, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE)
                            .addComponent(jTextFieldid)
                            .addComponent(jTextFieldtotalbiaya))))
                .addGap(0, 85, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(68, 68, 68)
                .addComponent(Tambah)
                .addGap(77, 77, 77)
                .addComponent(jButtonupdate)
                .addGap(76, 76, 76)
                .addComponent(jButtondelete)
                .addGap(63, 63, 63)
                .addComponent(jButtonclear)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelid)
                            .addComponent(jTextFieldid, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(9, 9, 9)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelnama)
                            .addComponent(jTextFieldnama, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(15, 15, 15)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabelnama1)
                            .addComponent(jTextFieldkontak, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeljenismobil)
                            .addComponent(jTextFieldjenismobil, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(21, 21, 21)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeldurasi)
                            .addComponent(jTextFielddurasi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabeltotalbiaya)
                            .addComponent(jTextFieldtotalbiaya, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelstatuspembayaran)
                            .addComponent(jTextFieldstatuspembayaran, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 47, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Tambah, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonupdate)
                    .addComponent(jButtondelete)
                    .addComponent(jButtonclear))
                .addGap(49, 49, 49))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldidActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldidActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldidActionPerformed

    private void jTextFieldstatuspembayaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldstatuspembayaranActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldstatuspembayaranActionPerformed

    private void jTextFieldtotalbiayaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldtotalbiayaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldtotalbiayaActionPerformed

    private void TambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TambahActionPerformed
        // TODO add your handling code here:
        rc.insert();
        rc.isiTabel();
    }//GEN-LAST:event_TambahActionPerformed

    private void jButtonupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonupdateActionPerformed
        // TODO add your handling code here:
        rc.update();
        rc.isiTabel();
    }//GEN-LAST:event_jButtonupdateActionPerformed

    private void jButtonclearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonclearActionPerformed
        // TODO add your handling code here:
        jTextFieldid.setText("");
        jTextFieldnama.setText("");
        jTextFieldkontak.setText("");
        jTextFieldjenismobil.setText("");
        jTextFieldtotalbiaya.setText("");
        jTextFieldstatuspembayaran.setText("");
    }//GEN-LAST:event_jButtonclearActionPerformed

    private void jTablerentalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTablerentalMouseClicked
        // TODO add your handling code here:
        int baris = jTablerental.getSelectedRow();
        
        
        
    }//GEN-LAST:event_jTablerentalMouseClicked

    private void jButtondeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtondeleteActionPerformed
        // TODO add your handling code here:
        rc.delete();
        rc.isiTabel();
    }//GEN-LAST:event_jButtondeleteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DashboardPage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DashboardPage().setVisible(true);
            }
        });
    }

    public RentalController getRc() {
        return rc;
    }

    public void setRc(RentalController rc) {
        this.rc = rc;
    }

    public JButton getTambah() {
        return Tambah;
    }

    public void setTambah(JButton Tambah) {
        this.Tambah = Tambah;
    }

    public JButton getjButtonclear() {
        return jButtonclear;
    }

    public void setjButtonclear(JButton jButtonclear) {
        this.jButtonclear = jButtonclear;
    }

    public JButton getjButtondelete() {
        return jButtondelete;
    }

    public void setjButtondelete(JButton jButtondelete) {
        this.jButtondelete = jButtondelete;
    }

    public JButton getjButtonupdate() {
        return jButtonupdate;
    }

    public void setjButtonupdate(JButton jButtonupdate) {
        this.jButtonupdate = jButtonupdate;
    }

    public JLabel getjLabeldurasi() {
        return jLabeldurasi;
    }

    public void setjLabeldurasi(JLabel jLabeldurasi) {
        this.jLabeldurasi = jLabeldurasi;
    }

    public JLabel getjLabelid() {
        return jLabelid;
    }

    public void setjLabelid(JLabel jLabelid) {
        this.jLabelid = jLabelid;
    }

    public JLabel getjLabeljenismobil() {
        return jLabeljenismobil;
    }

    public void setjLabeljenismobil(JLabel jLabeljenismobil) {
        this.jLabeljenismobil = jLabeljenismobil;
    }

    public JLabel getjLabelnama() {
        return jLabelnama;
    }

    public void setjLabelnama(JLabel jLabelnama) {
        this.jLabelnama = jLabelnama;
    }

    public JLabel getjLabelnama1() {
        return jLabelnama1;
    }

    public void setjLabelnama1(JLabel jLabelnama1) {
        this.jLabelnama1 = jLabelnama1;
    }

    public JLabel getjLabelstatuspembayaran() {
        return jLabelstatuspembayaran;
    }

    public void setjLabelstatuspembayaran(JLabel jLabelstatuspembayaran) {
        this.jLabelstatuspembayaran = jLabelstatuspembayaran;
    }

    public JLabel getjLabeltotalbiaya() {
        return jLabeltotalbiaya;
    }

    public void setjLabeltotalbiaya(JLabel jLabeltotalbiaya) {
        this.jLabeltotalbiaya = jLabeltotalbiaya;
    }

    public JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    public void setjScrollPane1(JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    public JTable getjTablerental() {
        return jTablerental;
    }

    public void setjTablerental(JTable jTablerental) {
        this.jTablerental = jTablerental;
    }

    public JTextField getjTextFielddurasi() {
        return jTextFielddurasi;
    }

    public void setjTextFielddurasi(JTextField jTextFielddurasi) {
        this.jTextFielddurasi = jTextFielddurasi;
    }

    public JTextField getjTextFieldid() {
        return jTextFieldid;
    }

    public void setjTextFieldid(JTextField jTextFieldid) {
        this.jTextFieldid = jTextFieldid;
    }

    public JTextField getjTextFieldjenismobil() {
        return jTextFieldjenismobil;
    }

    public void setjTextFieldjenismobil(JTextField jTextFieldjenismobil) {
        this.jTextFieldjenismobil = jTextFieldjenismobil;
    }

    public JTextField getjTextFieldkontak() {
        return jTextFieldkontak;
    }

    public void setjTextFieldkontak(JTextField jTextFieldkontak) {
        this.jTextFieldkontak = jTextFieldkontak;
    }

    public JTextField getjTextFieldnama() {
        return jTextFieldnama;
    }

    public void setjTextFieldnama(JTextField jTextFieldnama) {
        this.jTextFieldnama = jTextFieldnama;
    }

    public JTextField getjTextFieldstatuspembayaran() {
        return jTextFieldstatuspembayaran;
    }

    public void setjTextFieldstatuspembayaran(JTextField jTextFieldstatuspembayaran) {
        this.jTextFieldstatuspembayaran = jTextFieldstatuspembayaran;
    }

    public JTextField getjTextFieldtotalbiaya() {
        return jTextFieldtotalbiaya;
    }

    public void setjTextFieldtotalbiaya(JTextField jTextFieldtotalbiaya) {
        this.jTextFieldtotalbiaya = jTextFieldtotalbiaya;
    }


    public void setRootPaneCheckingEnabled(boolean rootPaneCheckingEnabled) {
        this.rootPaneCheckingEnabled = rootPaneCheckingEnabled;
    }

    public AccessibleContext getAccessibleContext() {
        return accessibleContext;
    }

    public void setAccessibleContext(AccessibleContext accessibleContext) {
        this.accessibleContext = accessibleContext;
    }

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tambah;
    private javax.swing.JButton jButtonclear;
    private javax.swing.JButton jButtondelete;
    private javax.swing.JButton jButtonupdate;
    private javax.swing.JLabel jLabeldurasi;
    private javax.swing.JLabel jLabelid;
    private javax.swing.JLabel jLabeljenismobil;
    private javax.swing.JLabel jLabelnama;
    private javax.swing.JLabel jLabelnama1;
    private javax.swing.JLabel jLabelstatuspembayaran;
    private javax.swing.JLabel jLabeltotalbiaya;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTablerental;
    private javax.swing.JTextField jTextFielddurasi;
    private javax.swing.JTextField jTextFieldid;
    private javax.swing.JTextField jTextFieldjenismobil;
    private javax.swing.JTextField jTextFieldkontak;
    private javax.swing.JTextField jTextFieldnama;
    private javax.swing.JTextField jTextFieldstatuspembayaran;
    private javax.swing.JTextField jTextFieldtotalbiaya;
    // End of variables declaration//GEN-END:variables

    
    
    
    public Object getjTableRental() {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }
}
